### ISSUE TITLE
models/recognize/code/saved/cont/best_checkpoint.pth文件下

### ISSUE THREAD

**Issue by Wangkailin27** [yccye/Auxiliary-diagnosis-system#1]
version https://git-lfs.github.com/spec/v1
oid sha256:a8b3407b40ea20df50bb6bf101a9163d048f761e24e318817cf922b7848e431f
size 194898920
如何下载pth文件

**Comment by ycycse** [comment]
这个是模型的权重文件，太大了无法上传

**Comment by ycycse** [comment]
可以邮箱联系我772781815@qq.com
